### ISSUE TITLE
Typo in article? 

### ISSUE THREAD

**Issue by claudehsu** [MicrosoftDocs/azure-devops-extensions#20]
The left-hand colored bar designates 'teh' state of each item

Is that a typo? :p

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e841ba7c-fa53-e50c-24d4-aef0d5d865e4
* Version Independent ID: a5abe379-3258-c90c-5599-dce78141bb44
* Content: [Dependency Tracker Timeline - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/extensions/dependency-tracker/timeline#feedback)
* Content Source: [extensions/dependency-tracker/Timeline.md](https://github.com/MicrosoftDocs/azure-devops-extensions/blob/live/extensions/dependency-tracker/Timeline.md)
* Product: **devops**
* GitHub Login: @cherylsingh
* Microsoft Alias: **chesing**

**Comment by chcomley** [comment]
I've addressed this issue in the linked PR. Thanks for your feedback!

#please-close
