### ISSUE TITLE
Link missing in Creating New Dependency Docs @ https://docs.microsoft.com/en-us/azure/devops/extensions/dependency-tracker/create-new-dependency

### ISSUE THREAD

**Issue by MerivaIe** [MicrosoftDocs/azure-devops-extensions#22]
No link after the text "To find Dependency tracker go to :"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 42c7973a-689d-28fb-3140-dd46c7afb4ef
* Version Independent ID: 8cf47564-c8f7-527b-a188-35131ac4ce13
* Content: [How to create a dependency - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/extensions/dependency-tracker/create-new-dependency)
* Content Source: [extensions/dependency-tracker/Create-new-dependency.md](https://github.com/MicrosoftDocs/azure-devops-extensions/blob/live/extensions/dependency-tracker/Create-new-dependency.md)
* Product: **devops**
* GitHub Login: @cherylsingh
* Microsoft Alias: **chesing**

**Comment by chcomley** [comment]
Thanks for your feedback. I've addressed this issue in the connected PR.

#please-close
