### ISSUE TITLE
Dependency Timeline not Working

### ISSUE THREAD

**Issue by joshuaquek** [MicrosoftDocs/azure-devops-extensions#23]
I cant get the lines to link between the different items, I have created a dependency already. 

Am I doing something wrong?

![image](https://user-images.githubusercontent.com/5335756/104292034-44a12980-54f7-11eb-8faf-0c12a98e627f.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e841ba7c-fa53-e50c-24d4-aef0d5d865e4
* Version Independent ID: a5abe379-3258-c90c-5599-dce78141bb44
* Content: [Dependency Tracker Timeline - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/extensions/dependency-tracker/timeline)
* Content Source: [extensions/dependency-tracker/Timeline.md](https://github.com/MicrosoftDocs/azure-devops-extensions/blob/live/extensions/dependency-tracker/Timeline.md)
* Product: **devops**
* GitHub Login: @cherylsingh
* Microsoft Alias: **chesing**

**Comment by joshuaquek** [comment]
No I haven't. The extension could possibly be broken, maybe?

**Comment by MarianoG8** [comment]
Hello. My dependency tracker timeline looks thus: 
![image](https://user-images.githubusercontent.com/64618777/134074550-f2d7e69a-a706-4a89-bc4a-aeede706d065.png)
Any help?

**Comment by chcomley** [comment]
We appreciate your contribution. Unfortunately, we have been unable to review this issue in a timely
manner. We sincerely apologize for the delayed response. We are closing this issue, however if you
feel the problem persists, please re-open the issue no later than 03/05/2024 with additional
information.

As we phase out GitHub issues for this repository, we encourage you to propose changes using public
PRs or submit feedback through our updated control at the top of the page. For more information on
our feedback systems, see https://aka.ms/ContentUserFeedback.

#please-close
