### ISSUE TITLE
Lack of links to additional information 

### ISSUE THREAD

**Issue by a-goo** [MicrosoftDocs/azure-devops-extensions#27]
Missing link to the marketplace page: https://marketplace.visualstudio.com/items?itemName=ms-eswm.dependencytracker&ssr=false#overview

Missing link to the documentation page: https://docs.microsoft.com/en-us/azure/devops/boards/extensions/dependency-tracker?view=azure-devops 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: de445062-63a5-24d9-cbb0-6c241a200c27
* Version Independent ID: 8a14afb2-d0f0-3878-96dc-3e72d8d717f4
* Content: [Overview of Dependency Tracker - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/extensions/dependency-tracker/overview)
* Content Source: [extensions/dependency-tracker/overview.md](https://github.com/MicrosoftDocs/azure-devops-extensions/blob/live/extensions/dependency-tracker/overview.md)
* Product: **devops**
* GitHub Login: @cherylsingh
* Microsoft Alias: **chesing**

**Comment by chcomley** [comment]
We appreciate your contribution. Unfortunately, we have been unable to review this issue in a timely
manner. We sincerely apologize for the delayed response. We are closing this issue, however if you
feel the problem persists, please re-open the issue no later than 03/05/2024 with additional
information.

As we phase out GitHub issues for this repository, we encourage you to propose changes using public
PRs or submit feedback through our updated control at the top of the page. For more information on
our feedback systems, see https://aka.ms/ContentUserFeedback.

#please-close
