### ISSUE TITLE
Clarification on predecessor link

### ISSUE THREAD

**Issue by gambrose** [MicrosoftDocs/azure-devops-extensions#37]
[Enter feedback here]

While you clarify the definition of predecessor and successor. It is not clear on which side of the relationship these terms apply.

I would expect that applying the predecessor link would have different connotation to the relationship based on which one of the two tickets it was applied.

So if you have two ticket one dependent on the other.
Should I:
* add the predecessor link to the dependent ticket with a link to the other ticket to mark is a dependancy of the other ticket.
* add the predecessor link to the other ticket with a link to the dependent ticket to say the linked ticket is the dependancy.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 42c7973a-689d-28fb-3140-dd46c7afb4ef
* Version Independent ID: 8cf47564-c8f7-527b-a188-35131ac4ce13
* Content: [How to create a dependency - Azure DevOps](https://learn.microsoft.com/en-us/azure/devops/extensions/dependency-tracker/create-new-dependency)
* Content Source: [extensions/dependency-tracker/Create-new-dependency.md](https://github.com/MicrosoftDocs/azure-devops-extensions/blob/live/extensions/dependency-tracker/Create-new-dependency.md)
* Service: **azure-devops**
* GitHub Login: @cherylsingh
* Microsoft Alias: **chesing**

**Comment by chcomley** [comment]
Hi @gambrose, thank you for reaching out. I've added some clarity to the article, which should be live within the next 24 hours. Here's what I added, essentially saying you can do either actions: 

Enter the Producer and Consumer work item IDs in the search boxes, or Create New work items.
- The Producer is the team that commits to deliver the work.
- The Consumer is the team that needs or is dependent on the work.
   For example:
   - From Team A (Producer/predecessor): Add a successor link to Task A. This signifies that Task A must finish before Task B can begin.
   - From Team B (Consumer/dependent): Add a predecessor link to Task B. This indicates that Task B cannot start until Task A is completed.
